/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "spi-violet-50": "#5F0047",
        "spi-violet-75": "#800762",
        "spi-violet-100": "#9B0D78",
        "spi-violet-200": "#E5C1DC",
        "spi-violet-300": "#FDECF9",
        "black-100": "#13020F",
        "black-200": "#666666",
        "black-300": "#CCCCCC",
        "black-400": "#F5F5F5",
        "spi-white-100": "#FFFFFF",
        "modal-100": "#FFFFFF",
        "site-backdrop": "#F7F4F7",
        "success-100": "0C5700",
        "success-200": "EFFFEC",
        "error-100": "#9F1818",
        "error-200": "#FFF3F3",
      },
      fontFamily: {
        sans: ["Poppins", "sans-serif"],
        title: ["Poppins", "sans-serif"],
        titleMobile: ["Poppins", "sans-serif"],
        heading1: ["Poppins", "sans-serif"],
        heading2: ["Poppins", "sans-serif"],
        heading3: ["Poppins", "sans-serif"],
        subHeading: ["Poppins", "sans-serif"],
        label: ["Poppins", "sans-serif"],
        labelM: ["Poppins", "sans-serif"],
        body1: ["Poppins", "sans-serif"],
        body2: ["Poppins", "sans-serif"],
        buttonPrimary: ["Poppins", "sans-serif"],
        buttonTertiary: ["Poppins", "sans-serif"],
        caption: ["Poppins", "sans-serif"],
        overline: ["Poppins", "sans-serif"],
      },
      fontSize: {
        title: "44px",
        titleMobile: "28",
        heading1: "22",
        heading2: "20",
        heading3: "16",
        subHeading: "12",
        label: "20",
        labelM: "14",
        body1: "20",
        body2: "16",
        buttonPrimary: "16",
        buttonTertiary: "16",
        caption: "14",
        overline: "12",
      },
      fontWeight: {
        title: "bold",
        titleMobile: "bold",
        heading1: "bold",
        heading2: "bold",
        heading3: "semibold",
        subHeading: "medium",
        label: "semibold",
        labelM: "medium",
        body1: "normal",
        body2: "normal",
        buttonPrimary: "semibold",
        buttonTertiary: "bold",
        caption: "normal",
        overline: "normal",
      },
      lineHeight: {
        title: "56px",
        titleMobile: "34px",
        heading1: "34px",
        heading2: "26px",
        heading3: "24px",
        subHeading: "13px",
        label: "28px",
        labelM: "24px",
        body1: "28px",
        body2: "24px",
        buttonPrimary: "24px",
        buttonTertiary: "24px",
        caption: "22px",
        overline: "14px",
      },
      letterSpacing: {
        title: "1.5%",
        titleMobile: "0%",
        heading1: "0%",
        heading2: "1.5%",
        heading3: "0%",
        subHeading: "1.5%",
        label: "0%",
        labelM: "0%",
        body1: "0%",
        body2: "0%",
        buttonPrimary: "0%",
        buttonTertiary: "2%",
        caption: "1.5%",
        overline: "0%",
      },
    },
  },
  plugins: [],
};
